---
title: "Bank Marketing Project"
author: "Jason Rupp and Yusi Zhang"
date: "8/1/2020"
output: html_document
---



## Introduction Required

## Data Description  Required

## Exploratory Analysis Required

Addressing Objective 1:
	Restatement of Problem and the overall approach to solve it Required

Model Selection Required
		Type of Selection
			Any or all:  LASSO, RIDGE, ELASTIC NET,
			Stepwise, Forward, Backward 
			Manual / Intuition		

		Checking Assumptions Required
                                        Lack of fit test
                                        Influential point analysis (Cook’s D and Leverage)
			Optional  Residual Plots
			
	Parameter Interpretation
		Interpretation  Required
		Confidence Intervals Required
	
Final conclusions from the analyses of Objective 1 Required


Addressing Objective 2
Make sure it is clear how many models were created to compete against the one in Objective 1.  Make note of any tuning parameters that were used and how you came up with them (knn and random forest logistics)  Required

Main Analysis Content Required
	Overall report of the error metrics on a test set or CV run.  Also if the two best models have error rates of .05 and .045,  can we really say that one model is outperforming the other?  For the ambitious, McNemar’s test could be helpful in answering that.

Conclusion/Discussion Required
		The conclusion should reprise the questions and conclusions of objective 2 with recommendations of the final model, what could be done to help analysis and model building in the future, and any insight as to why one method outshined all the rest if that is indeed the case.  If they all are similar why did you go with your final model?

Appendix Required
	Well commented SAS/R Code Required
 	Graphics and summary tables (Can be placed in the appendix or in the written report itself.)
